### ISSUE TITLE
[iKinGazeCtrl] Fix "random" spikes during control

### ISSUE THREAD

**Issue by vicentepedro** [vislab-tecnico-lisboa/vizzy#54]
The Gaze changes abruptly during some demos when the points are sent in a continuous way.

Possible problems:

- Target points with strange values.
- Bridge ROS/YARP, since this happens when controlling from ROS (we need to test with YARP).
- YARP BufferedPort reads only the last value (this can explain spikes during a sine trajectory).
- The operating system is not controlling in real time. 

/cc @joao-avelino

**Comment by plinioMoreno** [comment]
During the demo at the AHA project review meeting, the Gaze behavior was happening due to a wrong ROS network configuration (the env. var. ROS_MASTER_URI was not set properly), which caused network delays. 

So, the bridge ROS/YARP is the first option to check [fixationPointActionBridge](https://github.com/vislab-tecnico-lisboa/vizzy/blob/master/vizzy_yarp_icub/src/examples/iKinGaze_ROS_bridge/FixationPointRosAction.cpp). The subscriber created in this code, needs to be matched with the ROS Publisher at [Line 14 at GazeReal.cpp](https://github.com/vislab-tecnico-lisboa/vizzy/blob/master/vizzy_control/src/GazeReal.cpp#L14). After looking at the GazeReal.cpp, I think by changing the 1 in the publisher creation to 50 at least, should solve the problem, @joao-avelino @ruipimentelfigueiredo

**Comment by joao-avelino** [comment]
@plinioMoreno Did not solve the problem. The strange Gaze behavior is still happening at random times :(

**Comment by plinioMoreno** [comment]
Okay. Do you want to test a small change at [Line 41 of FixationPointRosAction.cpp ](https://github.com/vislab-tecnico-lisboa/vizzy/blob/master/vizzy_yarp_icub/src/examples/iKinGaze_ROS_bridge/FixationPointRosAction.cpp#L41), changing ```write()``` to ```writeStrict()```. You can play with both the buffer big and small on the ROS side.

If this does not change the behavior, then you will have to record a rosbag and at the same time save the yarp data using the ```yarpdatadumper``` and see what is wrong with the values. You can ask @vicentepedro or @gsaponaro for help on saving the data with the yarp data dumper.

**Comment by gsaponaro** [comment]
Just a small update on this matter:

Yesterday we tried the following approaches in the code for **FixationPointActionBridge**. Unfortunately, neither of them solved the problem:
- changing `write()` to `writeStrict()`
- changing the non-blocking read in the main spinning loop (i.e., `BufferedPort::read(false)` followed by a small delay at the end of the loop) to a blocking read (i.e., `BufferedPort::read(true)`)

The problem is reproducible, we recorded a yarp data dump, attached here: [fixPAB.zip](https://github.com/vislab-tecnico-lisboa/vizzy/files/1180580/fixPAB.zip). It can be played with **yarpdataplayer** (similar to **rosbag play**) and plotted with **yarpscope** (similar to **rqt_plot**).

**Comment by plinioMoreno** [comment]
In order to check if the problem was on the bridge, I used the following code that sends the points in YARP directly to the gaze controller:

```
#include <iostream>
#include <yarp/os/all.h>
#include <math.h>
#include <geometry_msgs_PointStamped.h>

using namespace yarp::os;

int main(int argc, char *argv[]) {
  Network yarp;
  BufferedPort<Bottle>  receiverBuff1Mux1;
  bool sender = receiverBuff1Mux1.open("/my_other_port_in");
  
  if(!sender)
  {
    printf(" failed to open\n");
    return -1;
  }

  bool connectSuccess = false;
  int i=0;
  while(!connectSuccess)
  {
    printf("\nTrying to connect to /iKinGazeCtrl/xd:i ... ");
    connectSuccess = yarp.connect(receiverBuff1Mux1.getName(),"/iKinGazeCtrl/xd:i");
    yarp::os::Time::delay(1);
  }
  double step_size=0.1/5;
  double rate=10.0;
  //double t0 = Time::now();
  // spinning
  while(true)
  {
    i++;

    Bottle *message = new Bottle();
    double angular_freq=2*3.141592*step_size;
    double time_instant=(double)i;
    double aux=angular_freq*time_instant;
    for(int i = 0; i < 3; i++) {
       message->add(-4.81938);
       message->add(3*cos(aux));
       message->add(0.449058);
    }
    Bottle & out = receiverBuff1Mux1.prepare();
        out = *message;
        receiverBuff1Mux1.write();
    yarp::os::Time::delay(1/rate);
  }
  return 0;
}
```
The problem persists, so the issue now is on the iKinGazeCtrl side. To alleviate the problem (it happens less frequently), the frequency of the point sender should be reduced to 10Hz. However, the frequency is not the only variable in this problem, the distance between points also has an effect. If the distance between points is too large, weird motions also happen. In fact the controller is not designed for points that are too far away from each other.

Next step is to check if the controller's parameters can be changed to alleviate the behavior.

**Comment by plinioMoreno** [comment]
By using the gaze client in commit dbfb14a78940ecb6225b38972066632c35fb50c5, this issue is finally gone for good.

"No hay mal que dure cien años ni cuerpo que lo resista"
